### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by enumag** [mhujer/jms-serializer-uuid#14]
Found a bug. I accidentally had `{}` in place of an uuid in request payload and deserialization failed on array to string conversion here: https://github.com/mhujer/jms-serializer-uuid/blob/9c669d7582266360f2e16b411b12d8f0dddec5fc/src/Uuid/UuidSerializerHandler.php#L61

**Comment by mhujer** [comment]
@enumag thanks for the report, I will fix it later. It would be easier to fix after I drop support for PHP <8.0, so I can use `Stringable` (https://github.com/mhujer/jms-serializer-uuid/commit/5d91e18c229d9bb00005660f50dae7d593d1e00f)

**Comment by enumag** [comment]
I would have sent a PR with a fix but I'm unsure how to handle the exceptions since DeserializationInvalidValueException requires a previous one and InvalidUuidException requires invalid value as string. There clearly needs to be some change here but not exactly sure what.

**Comment by mhujer** [comment]
@enumag fixed in #17 and release as 3.4.1.

btw. while I was checking how is this check implemented in the JMS serializer itself I realized that it isn't and DateTime deserializer emits "array to string conversion" in the similar situation.

**Comment by enumag** [comment]
@mhujer I see. I'd like to report that too but can't find the class responsible for deserializing datetime there. Do you know where it is?

**Comment by enumag** [comment]
Thanks! I reported that too then.
